### ISSUE TITLE
Compressed instructions should only be in the march string in the gcc command in Makefile when trying to run compressed tests

### ISSUE THREAD

**Issue by davidharrishmc** [openhwgroup/cvw-arch-verif#184]
Right now, Makefile is creating compressed instructions for RV32Zfh and other tests when it is not intended.  These tests should not depend on having compressed instructions available.

	riscv64-unknown-elf-gcc -g -o $@ -march=rv64gq$(CMPR_FLAG)_zfa_zba_zbb_zbc_zbs_zfh_zicboz_zicbop_zicbom_zicond -mabi=lp64 -mcmodel=medany \
	    -nostartfiles -T${WALLY}/examples/link/link.ld $<

**Comment by Zain2050** [comment]
I'll look into it. Is this happening to many Zfh tests or just one?

**Comment by davidharrishmc** [comment]
The compressed instructions went away in rv32/Zfh/WALLY-COV-ALL.elf.objdump.  Not quite sure why they came and went, but let's close this for now.
