### ISSUE TITLE
Issue with Cryptography Instructions

### ISSUE THREAD

**Issue by Daniyal-R-A** [openhwgroup/cvw-arch-verif#285]
Make sim is  giving error, if two extensions have same instructions. But as suggested in the 000_RISCV_summary-bitmanip_amo.pdf 
"Zknd and Zkne (RV64 only): AES Key Schedule" has the same Instructions as shown below:
![image](https://github.com/user-attachments/assets/9b25d6df-d888-448f-96d4-c8613fee15bb)

Same issue with Zbkb extension as it saying that it "also includes rolw, rorw, rorrwi, Table I.23, which are instructions for Zbb RV64:
![image](https://github.com/user-attachments/assets/9da9bc1d-ec2a-4a89-82e4-dc40b129e51d)
 

Also no instructions are listed for Zbkc extension:
![image](https://github.com/user-attachments/assets/5926f0f9-825c-43bd-a594-b66ee30560e5)

**Comment by davidharrishmc** [comment]
These instructions that belong to multiple extensions only need to be tested once.  Let's keep this issue open.  Once the tests are created, let's think about the best way to run the appropriate tests for the appropriate extensions.

**Comment by jordancarlin** [comment]
A potentially simple solution for the covergroups is to put instructions that are shared by more than one extension in their own file (like `RV64ZKND_OR_ZKNE`), wrap that file in an include guard, and then include if within both of the main extension files that contain those instructions. The include guard would prevent the extensions from being defined twice if both of the extensions are supported.

**Comment by davidharrishmc** [comment]
These files are all autogenerated, so if we have an include guard, the autogeneration logic needs to know where to apply it.

**Comment by jordancarlin** [comment]
That does complicate it. Could maybe have known cases of this is their own CSV files separate from the main one for the extension and just hardcode in a list of CSVs that covergroupgen.py adds extra include guards in. Or maybe even have covergroupgen wrap all of the generated files in include guards (never a bad idea) and then the special case logic just needs to be having it add including the extra file in the main extension file.

**Comment by davidharrishmc** [comment]
Works after the refactoring added extension names to covergroups.
