### ISSUE TITLE
fli cannot create raw hazards

### ISSUE THREAD

**Issue by HamzaYusufJamal** [openhwgroup/cvw-arch-verif#323]
PR #322 implements hazard testing for all float instructions, but some instructions like fli cannot trigger certain types of hazards, leading to a false sub-100% coverage report. This issue serves to keep track of the required change for a fix.

**Comment by davidharrishmc** [comment]
It's ok that fli can't create raw hazards.  Can you modify the coverpoint used for fli so you don't try to hit them?
