### ISSUE TITLE
Random Number Generator Seeding

### ISSUE THREAD

**Issue by coreyqh** [openhwgroup/cvw-arch-verif#376]
Per ACTs meeting on 12/16, it would be helpful to have RNG seeding to ensure that tests can be reproduced arbitrarily far in the future. This would be helpful for debugging by allowing users to easily recreate mismatching test programs. Currently, any time testgen.py is modified, all pseudo random values generated by the script change.

**Comment by davidharrishmc** [comment]
Resolved with PR #374 
```
def write_tests(coverpoints, test, xlen):
  for coverpoint in coverpoints:
    # produce a deterministic seed for repeatable random numbers 
    # distinct for each instruction and coverpoint
    seed(hash(test + coverpoint)) 
```
