### ISSUE TITLE
Porting Privileged coverage files to Imperas ISACOV

### ISSUE THREAD

**Issue by Huda-10xe** [openhwgroup/cvw-arch-verif#56]
Change the VM and Zicbom coverage files to be added to fcov and run using the ISACOV flow
Change Zicbom cvg to remove exceptions covergroups and add them to a new file CBO_VM
Update Covergroups to be static to remove Questa warnings

**Comment by davidharrishmc** [comment]
@Huda-10xe I think you said you made progress on integrating the VM tests.  Could you make a PR before the Tuesday review with whatever changes are needed to make VM tests part of regression-wally --fcov?

**Comment by Huda-10xe** [comment]
Sorry for the late PR, we ran into some unforeseen issues, but everything has been resolved now. PR#993 for cvw and PR#171 for cvw-arch-verif resolve this issue
