### ISSUE TITLE
Connecting CSRs in ISACOV Tracer

### ISSUE THREAD

**Issue by Huda-10xe** [openhwgroup/cvw-arch-verif#57]
Currently the RISCV_INSTRUCTION class only assigns values to rs1, rs2, rd and imm but not to csrs.
Populate the functions in this class to get csr values to be used in coverage of privileged features

**Comment by Huda-10xe** [comment]
The **add_csr** method calls **rvviRefCsrIndex** but I can't find its definition anywhere.

**Comment by davidharrishmc** [comment]
@Huda-10xe it looks like you can observe CSRs now.  Can you close this if you are satisfied?
